function indices = matchFlangeJoints(detectedZ,nominalZ,isFlangeJoint)
% Match flange connections by elevation, never by position in the peak list.
detectedZ = detectedZ(:);
nominalZ = nominalZ(:);
if numel(nominalZ) ~= numel(isFlangeJoint) || ...
        any(~isfinite(nominalZ)) || any(diff(nominalZ) <= 0) || ...
        any(~isfinite(detectedZ)) || any(diff(detectedZ) <= 0)
    error('matchFlangeJoints:InvalidJoints','Joint elevations must be finite and strictly increasing.')
end
indices = [];
for nominalIndex = find(isFlangeJoint(:))'
    if nominalIndex == 1 || nominalIndex == numel(nominalZ)
        error('matchFlangeJoints:ClippedFlange', ...
            'Flange connection at %.3f m needs neighbouring joints on both sides. Extend the height range.', ...
            nominalZ(nominalIndex))
    end
    % Midpoints separate the flange connection from its adjacent welds.
    lower = mean(nominalZ(nominalIndex-1:nominalIndex));
    upper = mean(nominalZ(nominalIndex:nominalIndex+1));
    candidate = find(detectedZ > lower & detectedZ < upper);
    if numel(candidate) ~= 1
        error('matchFlangeJoints:UnresolvedFlange', ...
            'Flange connection at %.3f m has %g candidate peaks between %.3f and %.3f m. Check Stage 2 detection.', ...
            nominalZ(nominalIndex),numel(candidate),lower,upper)
    end
    if candidate == 1 || candidate == numel(detectedZ) || ...
            detectedZ(candidate-1) <= nominalZ(nominalIndex-1)- ...
                (nominalZ(nominalIndex)-nominalZ(nominalIndex-1))/2 || ...
            detectedZ(candidate+1) >= nominalZ(nominalIndex+1)+ ...
                (nominalZ(nominalIndex+1)-nominalZ(nominalIndex))/2
        error('matchFlangeJoints:MissingFlangeWeld', ...
            'Flange connection at %.3f m lacks nearby weld peaks on both sides. Check Stage 2 detection.', ...
            nominalZ(nominalIndex))
    end
    indices(end+1) = candidate; %#ok<AGROW>
    fprintf('Stage 2: flange connection at nominal %.3f m matched to peak %g (%.3f m).\n', ...
        nominalZ(nominalIndex),candidate,detectedZ(candidate))
end
end
